
[Options]
	# If you have existing tamed vanilla cats in your world and want to change them to Simply Cats, enable this and restart your minecraft instance.
	replace_tamed_vanilla = true
	# Disables vanilla cats spawning, set to false to allow them to spawn again.
	stop_vanilla_spawns = true
	# Disable this if you want ALL stray village cats to be fixed (enable for 10% intact cat spawns).
	intact_stray_spawns = true
	# Disabling this will not allow cats to attack entities in their prey list, essentially a peaceful mode for cats.
	attack_ai = true
	# When a cat's home is set, this is the radius in blocks they are allowed to roam around it.
	# Default: 32.0
	wander_area_limit = 32.0
	# Sets a limit of cats each player is allowed to have tamed, setting this to 0 will disable the limit.
	tamed_limit = 0
	# This number is used to limit cat breeding; if more than this amount of cats are nearby, automatic breeding will be disabled.
	# Default: 20
	breeding_limit = 20

[Timers]
	# Number of minecraft ticks before a kitten becomes an adult.
	# Default: 168000 (7 full minecraft days)
	kitten_mature_timer = 168000
	# Number of minecraft ticks before a pregnant cat will give birth.
	# Default: 96000 (4 full minecraft days)
	pregnancy_timer = 96000
	# Number of minecraft ticks that a cat will be in heat.
	# Default: 48000 (2 full minecraft days)
	heat_timer = 48000
	# Number of minecraft ticks that a cat will not go into heat.
	# Default: 384000 (16 full minecraft days)
	heat_cooldown = 384000
	# Number of minecraft ticks that a male cat will not try to breed after breeding once already.
	# Default: 6000 (1/4th minecraft day)
	male_cooldown = 6000

[Lists]
	# This is a list of entities all cats will attack on sight if cat attack AI is enabled.
	prey_list = ["minecraft:bat", "minecraft:parrot", "minecraft:chicken", "minecraft:rabbit", "minecraft:parrot", "minecraft:silverfish", "rats:rat", "zawa:brown_rat", "zawa:macaw", "zawa:black_footed_ferret", "zawa:kakapo", "zawa:butterfly", "exoticbirds:woodpecker", "birdwmod:brown_booby", "birdwmod:eastern_bluebird", "birdwmod:eurasian_bullfinch", "birdwmod:great_grey_owl", "birdwmod:green_heron", "birdwmod:hoatzin", "birdwmod:killdeer", "birdwmod:kingofsaxony_bird_of_paradise", "birdwmod:northern_mockingbird", "birdwmod:redflanked_bluetail", "birdwmod:rednecked_nightjar", "birdwmod:stellers_eider", "birdwmod:turquoisebrowed_motmot", "exoticbirds:bluejay", "exoticbirds:booby", "exoticbirds:budgerigar", "exoticbirds:cardinal", "exoticbirds:duck", "exoticbirds:gouldianfinch", "exoticbirds:hummingbird", "exoticbirds:kingfisher", "exoticbirds:kiwi", "exoticbirds:kookaburra", "exoticbirds:lyrebird", "exoticbirds:magpie", "exoticbirds:parrot", "exoticbirds:pigeon", "exoticbirds:roadrunner", "exoticbirds:robin", "exoticbirds:toucan", "animania:hamster", "animania:frog", "animania:toad", "animania:buck_cottontail", "animania:doe_cottontail", "animania:kit_cottontail", "animania:buck_chinchilla", "animania:doe_chinchilla", "animania:kit_chinchilla", "animania:buck_dutch", "animania:doe_dutch", "animania:kit_dutch", "animania:buck_havana", "animania:doe_havana", "animania:kit_havana", "animania:buck_jack", "animania:doe_jack", "animania:kit_jack", "animania:buck_new_zealand", "animania:doe_new_zealand", "animania:kit_new_zealand", "animania:buck_rex", "animania:doe_rex", "animania:kit_rex", "animania:buck_lop", "animania:doe_lop", "animania:kit_lop", "animania:rooster_leghorn", "animania:rooster_orpington", "animania:rooster_plymouth_rock", "animania:rooster_rhode_island_red", "animania:rooster_wyandotte", "animania:hen_leghorn", "animania:hen_orpington", "animania:hen_plymouth_rock", "animania:hen_rhode_island_red", "animania:hen_wyandotte", "animania:chick_leghorn", "animania:chick_orpington", "animania:chick_plymouth_rock", "animania:chick_rhode_island_red", "animania:chick_wyandotte"]

